### ISSUE TITLE
Linux系统下无法选择Java

### ISSUE THREAD

**Issue by imfine2333** [Blessing-Studio/WonderLab#1]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab/issues) 列表中是否有相似问题
- [x] 查看 [Releases](https://github.com/Blessing-Studio/WonderLab/releases) 中最新版是否已修复你所遇到的问题

### 问题描述

Linux系统下选择Java无法选择文件夹只能Open

### 问题复现率

必现

### 复现步骤

1.在Linux下打开启动器
2.转到设置界面
3.点击“Java设置”下的“浏览”

### 操作系统版本

OpenSUSE Tumbleweed x86_64

### WonderLab版本

1.0.8

**Comment by mailset** [comment]
正在写此功能

**Comment by weitcis** [comment]
https://github.com/Blessing-Studio/WonderLab/blob/933a58aea626d356254a92eaa0499a6400c2f565/WonderLab/ViewModels/GameSettingViewModel.cs#L187-L189

**Comment by Blessing-Studio** [comment]
此问题已修复
