### ISSUE TITLE
又乱码了。。。

### ISSUE THREAD

**Issue by Starcloudsea** [Blessing-Studio/WonderLab#16]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab/issues) 列表中是否有相似问题
- [x] 查看 [Releases](https://github.com/Blessing-Studio/WonderLab/releases) 中最新版是否已修复你所遇到的问题

### 问题描述

![image](https://user-images.githubusercontent.com/84891987/213848131-23462045-47f7-45cc-9602-ef7005935b90.png)
自己看吧（

### 问题复现率

必现

### 复现步骤

打开祝福终端就可以看到

### 操作系统版本

Windows

### WonderLab版本

1.0.1.4

**Comment by weitcis** [comment]
macOS 下可以复现此bug，但显示方式略有不同：

<img width="954" alt="CleanShot 2023-01-21 at 15 17 30@2x" src="https://user-images.githubusercontent.com/25654046/213894119-50595a45-b84e-4b56-81ab-b4902e3eaf6d.png">
<img width="947" alt="74da0a84613def0f5ae92ca2eb8b2e58" src="https://user-images.githubusercontent.com/25654046/213894126-fdd6101e-4888-4305-bf8b-4b23c32261b3.png">

**Comment by hei-shou** [comment]
已修复
