### ISSUE TITLE
大 型 i s s u e s

### ISSUE THREAD

**Issue by Starcloudsea** [Blessing-Studio/WonderLab#17]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab/issues) 列表中是否有相似问题
- [X] 查看 [Releases](https://github.com/Blessing-Studio/WonderLab/releases) 中最新版是否已修复你所遇到的问题

### 问题描述

1，第三方登录输入这按确定就会崩溃：
![image](https://user-images.githubusercontent.com/84891987/213848351-68859a5a-d7a5-4b57-90f6-a55fe04f3428.png)
2，这个.....改不了吗？
![image](https://user-images.githubusercontent.com/84891987/213848372-4381376d-1ad0-4cc5-bb16-6075e33b63b2.png)
3，一直乱按侧边栏按钮还是会崩溃（估计是Avalonia的锅）
4，打开启动器时会发现一个框，在极短的时间后又消失了
5，Java路径随便选择一个程序（比如下面这个）再启动游戏会崩溃（就怕有人直接选择了Java安装包）
![image](https://user-images.githubusercontent.com/84891987/213848523-9677c5b0-d488-4668-95b7-faa668885a20.png)
6，游戏目录设置添加一个游戏目录再移除就会崩溃（Java的话如果你选择了错误的程序也会崩）
7，在Java设置里，我 改 变 不 了 我 的 J A V A 路 径 ！（那个Combobox不让我选择）（这个只是偶尔复现）
8，删除一个版本，却根本删不了，还给整崩溃了
9，没网状态下，你的启动器貌似 打 不 开
10，如果你输入了错误的附加JVM参数，启动器也会崩崩

### 问题复现率

必现

### 复现步骤

我在上文说明了

### 操作系统版本

Windows

### WonderLab版本

1.0.1.4

**Comment by xiaoniaoawa** [comment]
哈哈哈哈草

**Comment by JWJUN233233** [comment]
c 现在就开始修

**Comment by xiaoniaoawa** [comment]
哈哈哈哈草

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Ddggdd135 ***@***.***>
发送时间: Saturday, January 21, 2023 4:11:05 PM
收件人: Blessing-Studio/WonderLab ***@***.***>
抄送: xiaoniao_ ***@***.***>; Comment ***@***.***>
主题: Re: [Blessing-Studio/WonderLab] 大 型 i s s u e s (Issue #17)


c 现在就开始修

―

**Comment by Starcloudsea** [comment]
过年了，休息会（

**Comment by xiaoniaoawa** [comment]
h


获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Starcloudsea ***@***.***>
发送时间: Saturday, January 21, 2023 4:12:10 PM
收件人: Blessing-Studio/WonderLab ***@***.***>
抄送: xiaoniao_ ***@***.***>; Comment ***@***.***>
主题: Re: [Blessing-Studio/WonderLab] 大 型 i s s u e s (Issue #17)


过年了，休息会（

―

**Comment by Blessing-Studio** [comment]
所有 Bug 均已修复
