### ISSUE TITLE
更大的[issues]!

### ISSUE THREAD

**Issue by Starcloudsea** [Blessing-Studio/WonderLab#18]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab/issues) 列表中是否有相似问题
- [X] 查看 [Releases](https://github.com/Blessing-Studio/WonderLab/releases) 中最新版是否已修复你所遇到的问题

### 问题描述

1，从【别的启动器】下载的Minecraft（比如PCL），一启动会把【启动器崩掉！】（啊当然自家下载的也是）
2，【完成】了？怎么条没有【满】啊？（偶尔发生）
![image](https://user-images.githubusercontent.com/84891987/213871635-397878aa-6350-4ec0-88f6-d462240dfa89.png)
3，刚在启动器下载的1.19.3......那是不会启动成功的因为......
![image](https://user-images.githubusercontent.com/84891987/213871729-246249ea-52c1-4cea-9eea-ed63e87850dd.png)
4,在【这样】的情况下【转至控制台】......如您所见（
![image](https://user-images.githubusercontent.com/84891987/213871769-af18c02e-01bf-4064-b228-05ca6e64fdbd.png)
5，没有新任务，但【这】啥情况？？？（安装途中x掉任务）
![image](https://user-images.githubusercontent.com/84891987/213896731-20143ac3-8dfa-4fac-9d2f-8235b761d9cd.png)
6，拖动【最大线程数】时，我根本看不到【数字】，这怎么让人知道我调了多少？
7，又是【乱码】！
![image](https://user-images.githubusercontent.com/84891987/213872462-ec9b3859-4bb0-4120-9dbb-05830474c76c.png)
8，在【下载Mod】里能找到【整合包】，但是你为什么直接把【整合包】下到【Mod文件夹】里？
![image](https://user-images.githubusercontent.com/84891987/213872608-5f9d3da6-5b5a-4ca7-91bb-dfd7684ea325.png)
9，【版本文件夹】经常未响应，何不给它做个【小小的加载条】？
10，字变白了！
![image](https://user-images.githubusercontent.com/84891987/213872909-0e8d3379-d05b-4143-9c62-85e5e98fdd74.png)、
11，你更改不了【版本名】！会崩崩！（
12，你在【游戏列表】里随便找个版本，点击【设置】，再点击【启动该核心】，为什么会导航到这个版本的【属性】里？
13，[这个！](https://vdse.bdstatic.com/192d9a98d782d9c74c96f09db9378d93.mp4)

### 问题复现率

必现

### 复现步骤

上文说了

### 操作系统版本

Windows

### WonderLab版本

1.0.1.4

**Comment by geenh** [comment]
叠词词，恶心心(((@Starcloudsea

**Comment by Blessing-Studio** [comment]
所有问题均已修复：喜）
