### ISSUE TITLE
[建议]功能添加与优化

### ISSUE THREAD

**Issue by xiaoniaoawa** [Blessing-Studio/WonderLab#2]
1.Java自动选择：
--判断用户是否单独指定了该版本的Java
---是
----按指定的Java启动
---否
----启动器检测游戏版本
----如果游戏版本=1.17
-----使用Java17，否则18，再其次8
----如果游戏版本>1.17
-----使用Java18，否则17，否则8
----如果游戏版本<1.17
-----使用Java8，否则17，否则8

2.UI优化
--请 适 配 平 滑 字 体(我屏幕分辨率1600*900，锯齿感极强)

3.安装核心
--你这按名称不如改名按应用范围...全是常用版本

**Comment by xiaoniaoawa** [comment]
啊对了，最好做个启动器内更新
比如写个菜单，点检查更新后从Github某个文件拉取目前最新版本，和目前作比较，不一样就确认、下载、一气呵成。一样就提示没更新...

**Comment by JWJUN233233** [comment]
最后这句话没听懂 能换个说法吗？其他的我计划明天做 UI等黑 手做

**Comment by JWJUN233233** [comment]
> 啊对了，最好做个启动器内更新
> 
> 比如写个菜单，点检查更新后从Github某个文件拉取目前最新版本，和目前作比较，不一样就确认、下载、一气呵成。一样就提示没更新...

github的API我不熟悉 等我学了再说

**Comment by JWJUN233233** [comment]
> 啊对了，最好做个启动器内更新 比如写个菜单，点检查更新后从Github某个文件拉取目前最新版本，和目前作比较，不一样就确认、下载、一气呵成。一样就提示没更新...

已完成 请下载最新版

**Comment by JWJUN233233** [comment]
字体这个没法弄 你分辨率实在是太低了 1080p都没有
