### ISSUE TITLE
寻找Java的思路

### ISSUE THREAD

**Issue by 1526lk** [Blessing-Studio/WonderLab#21]
### 建议描述

Linux大多数发行版有一个指令
叫grep
如果用ls列出所有文件夹然后grep java可能实现寻找java

### 操作系统版本

Linux

### WonderLab版本

1.0.1.4

**Comment by hei-shou** [comment]
回头试试

**Comment by mailset** [comment]
ls效率很低，不如用find /usr/lib/jvm -name java 2> /dev/null
