### ISSUE TITLE
检查更新有bug(点击"×"会未响应&有两个重复的提示)

### ISSUE THREAD

**Issue by FallingSand** [Blessing-Studio/WonderLab#22]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab/issues) 列表中是否有相似问题
- [X] 查看 [Releases](https://github.com/Blessing-Studio/WonderLab/releases) 中最新版是否已修复你所遇到的问题

### 问题描述

![Snipaste_2023-01-22_21-18-53](https://user-images.githubusercontent.com/74666734/213917977-6d84b63f-7132-4c8d-a1be-bc6cb8263458.png)
点击"×"会未响应&有两个重复的提示

### 问题复现率

高偶发

### 复现步骤

![Snipaste_2023-01-22_21-21-56](https://user-images.githubusercontent.com/74666734/213918145-63cf4561-a1f6-4c71-a69f-991eceaabd93.png)
_点击后_程序就会**未响应** 然后**闪退**

### 操作系统版本

Windows

### WonderLab版本

1.0.1.4

**Comment by JWJUN233233** [comment]
这个不是bug

**Comment by JWJUN233233** [comment]
实在想改的话也改不了 ui框架背锅

**Comment by JWJUN233233** [comment]
暂时新版已经没有发现这个问题了
