### ISSUE TITLE
mod过多导致属性选项卡中的mod显示不全&右侧滚动条有bug

### ISSUE THREAD

**Issue by FallingSand** [Blessing-Studio/WonderLab#23]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab/issues) 列表中是否有相似问题
- [X] 查看 [Releases](https://github.com/Blessing-Studio/WonderLab/releases) 中最新版是否已修复你所遇到的问题

### 问题描述

![image](https://user-images.githubusercontent.com/74666734/213918313-f1e4fe2c-8030-42f2-9fb7-60468c15e13a.png)
![image](https://user-images.githubusercontent.com/74666734/213918374-c94a33b3-b0c3-4e48-b49f-740056a888d7.png)

### 问题复现率

必现

### 复现步骤

只要mod够多就会发生
![image](https://user-images.githubusercontent.com/74666734/213918480-8ead3723-e080-403e-8d4e-a2a41457ba5a.png)

### 操作系统版本

Windows

### WonderLab版本

1.0.1.4

**Comment by hei-shou** [comment]
已修复
