### ISSUE TITLE
更改游戏核心名 上的“取消”文字颜色有问题(#18已提到

### ISSUE THREAD

**Issue by FallingSand** [Blessing-Studio/WonderLab#24]
### ❗ 检查表

-  搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab/issues) 列表中是否有相似问题
- [X] 查看 [Releases](https://github.com/Blessing-Studio/WonderLab/releases) 中最新版是否已修复你所遇到的问题

### 问题描述

![image](https://user-images.githubusercontent.com/74666734/213918652-3944159a-b68f-4a3d-af52-9f4db73f71de.png)
↑光标不在取消按钮上时
![image](https://user-images.githubusercontent.com/74666734/213918664-b1e2eeff-a6d1-4cbe-8af5-b8aaf327035a.png)
↑光标在取消按钮上时

### 问题复现率

必现

### 复现步骤

在“更改游戏核心名”窗口上当光标不在取消按钮上时没有“取消”二字（也有可能是“取消”二字的颜色和按钮背景色相同导致的）

### 操作系统版本

Windows

### WonderLab版本

1.0.1.4

**Comment by hei-shou** [comment]
已修复
