### ISSUE TITLE
离线用户名字长度没限制

### ISSUE THREAD

**Issue by FallingSand** [Blessing-Studio/WonderLab#26]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab/issues) 列表中是否有相似问题
- [X] 查看 [Releases](https://github.com/Blessing-Studio/WonderLab/releases) 中最新版是否已修复你所遇到的问题

### 问题描述

![image](https://user-images.githubusercontent.com/74666734/213919278-004a335e-7f7c-44bd-91ea-cf6e1e5ae6b0.png)

### 问题复现率

必现

### 复现步骤

↑ 写在title上了

### 操作系统版本

Windows

### WonderLab版本

1.0.1.4

**Comment by JWJUN233233** [comment]
这不算bug 这个算建议 请问你打算最大用户名是多长

**Comment by Puqns67** [comment]
用户名长度限制应为3-16字符，[官方帮助文档](https://help.minecraft.net/hc/en-us/articles/4408950195341-Minecraft-Java-Edition-Username-VS-Gamertag-FAQ#h_01GE5JWW0210X02JZN2FP9CREC)中就有提到这一点。
按照此文章中提到的几点，可以使用此正则进行判断: ```^[A-Za-z0-9_]{3,16}$```

**Comment by hei-shou** [comment]
好的，我们会在最近的构建版制作

**Comment by JWJUN233233** [comment]
> 用户名长度限制应为3-16字符，[官方帮助文档](https://help.minecraft.net/hc/en-us/articles/4408950195341-Minecraft-Java-Edition-Username-VS-Gamertag-FAQ#h_01GE5JWW0210X02JZN2FP9CREC)中就有提到这一点。
> 
> 按照此文章中提到的几点，可以使用此正则进行判断: ```^[A-Za-z0-9_]{3,16}$```

这样无法包含中文 有的服务器需要中文登陆 比如中国bbtt

**Comment by JWJUN233233** [comment]
我会在今天尝试修复

**Comment by Blessing-Studio** [comment]
好了

**Comment by Blessing-Studio** [comment]
你的议题已解决
感谢反馈
[点击这里反馈新问题](https://github.com/Blessing-Studio/WonderLab/issues/new/choose)
