### ISSUE TITLE
Deepin/UOS平台下无法安装

### ISSUE THREAD

**Issue by zkitefly** [Blessing-Studio/WonderLab#28]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab/issues) 列表中是否有相似问题
- [X] 查看 [Releases](https://github.com/Blessing-Studio/WonderLab/releases) 中最新版是否已修复你所遇到的问题

### 问题描述

![image](https://user-images.githubusercontent.com/64117916/214308323-ce377a94-9b1e-4604-89ec-6ad57ca1f47a.png)
```
zkitefly@zkitefly:/tmp/MicrosoftEdgeDownloads/e339cf3b-0332-43e8-8718-ffec83bfa4e6$ sudo apt install '/tmp/MicrosoftEdgeDownloads/e339cf3b-0332-43e8-8718-ffec83bfa4e6/linux-x86_64.deb'
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
注意，选中 'wonderlab' 而非 '/tmp/MicrosoftEdgeDownloads/e339cf3b-0332-43e8-8718-ffec83bfa4e6/linux-x86_64.deb'
有一些软件包无法被安装。如果您用的是 unstable 发行版，这也许是
因为系统无法达到您要求的状态造成的。该版本中可能会有一些您需要的软件
包尚未被创建或是它们已被从新到(Incoming)目录移出。
下列信息可能会对解决问题有所帮助：

下列软件包有未满足的依赖关系：
 wonderlab : 依赖: dotnet-runtime-6.0 但无法安装它
E: 无法修正错误，因为您要求某些软件包保持现状，就是它们破坏了软件包间的依赖关系。
zkitefly@zkitefly:/tmp/MicrosoftEdgeDownloads/e339cf3b-0332-43e8-8718-ffec83bfa4e6$ 

```

使用 Github Releases 中的 [1.0.1.4](https://github.com/Blessing-Studio/WonderLab/releases/tag/1.0.1.4)  版本

![image](https://user-images.githubusercontent.com/64117916/214309038-b6a1a31d-9514-4e63-a618-79cac78b1917.png)

似乎是依赖问题，但 `dotnet-runtime-6.0` 不知从何下载

### 问题复现率

必现

### 复现步骤

0.在 Deepin/UOS 平台下
1.从 [1.0.1.4](https://github.com/Blessing-Studio/WonderLab/releases/tag/1.0.1.4)  中下载 linux-x86_64.deb 
2.使用 `sudo apt install [DEB]` 进行安装

### 操作系统版本

Windows

### WonderLab版本

 [1.0.1.4](https://github.com/Blessing-Studio/WonderLab/releases/tag/1.0.1.4) 

### 插件信息

![image](https://user-images.githubusercontent.com/64117916/214309884-bcac4e51-dc9d-4b55-8897-55e413ce8171.png)

**Comment by hei-shou** [comment]
装个.NET6运行时就可以了，下载地址浏览器搜.NET6
