### ISSUE TITLE
关于自带运行时的一点看法

### ISSUE THREAD

**Issue by wuliangtdi** [Blessing-Studio/WonderLab#29]
建议可以弄两个版本的，一个独立发布的版本，一个依赖框架的版本，各取所需

**Comment by JWJUN233233** [comment]
这个估计无法实现 而且装runtime不好吗

**Comment by JWJUN233233** [comment]
.net程序必须依赖框架

**Comment by wuliangtdi** [comment]
steam++也是用.net开发的，ui框架也用的是这个avalonia，是有独立发布的应用程序。按理来说应该是可以独立发布的。

**Comment by wuliangtdi** [comment]
我看有人安装不上运行时，就想着这个是可以独立发布的，应该可以解决一部分人的问题。
