### ISSUE TITLE
接着上个建议

### ISSUE THREAD

**Issue by wuliangtdi** [Blessing-Studio/WonderLab#30]
我记得steam++也是用的 .net，ui框架也是用的avalonia，他们是可以独立发布。所以这个应该也是可以独立发布的。我是看着有些人安装不上运行时，所以就提了提这个。老哥你关闭的速度太快了😭😭

**Comment by JWJUN233233** [comment]
az

**Comment by wuliangtdi** [comment]
我试着编译独立发布的版本，结果发布不了，出错了。依赖框架的也是会出错，不知道为啥
![5QUK)JH FN~6A}VXWX6)Y P](https://user-images.githubusercontent.com/50443578/214473726-bf92d022-c8b2-49be-937f-73af22e4b354.png)

![MGEYOJ_J@NQ5R@N `DT1L`5](https://user-images.githubusercontent.com/50443578/214473782-20e01c2e-727a-4348-b10d-90e5fa9c7846.png)

**Comment by JWJUN233233** [comment]
暂时无法做到
Updata这个项目我以后会考虑放在WonderLab内部 就不会出错了

**Comment by JWJUN233233** [comment]
updata已经被拔掉了

**Comment by JWJUN233233** [comment]
你再试试

**Comment by Blessing-Studio** [comment]
你的议题已解决
感谢反馈
[点击这里反馈新问题](https://github.com/Blessing-Studio/WonderLab/issues/new/choose)
