### ISSUE TITLE
删除核心功能出错

### ISSUE THREAD

**Issue by EdkaClayEn** [Blessing-Studio/WonderLab#31]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab/issues) 列表中是否有相似问题
- [X] 查看 [Releases](https://github.com/Blessing-Studio/WonderLab/releases) 中最新版是否已修复你所遇到的问题

### 问题描述

删除核心必须在“属性”页面才能生效，游戏列表里点击对应版本核心旁边的齿轮删除无效

### 问题复现率

高偶发

### 复现步骤

问题描述里已经说了

### 操作系统版本

Windows

### WonderLab版本

1.0.1.6

### 插件信息

无

### 补充信息

无

**Comment by Blessing-Studio** [comment]
你的议题已解决
感谢反馈
[点击这里反馈新问题](https://github.com/Blessing-Studio/WonderLab/issues/new/choose)
