### ISSUE TITLE
自动更新出问题啦

### ISSUE THREAD

**Issue by Starcloudsea** [Blessing-Studio/WonderLab#32]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab/issues) 列表中是否有相似问题
- [X] 查看 [Releases](https://github.com/Blessing-Studio/WonderLab/releases) 中最新版是否已修复你所遇到的问题
- [X] 查看 [Actions](https://github.com/Blessing-Studio/WonderLab/Actions) 中最新Dev版是否已修复你所遇到的问题

### 问题描述

在内测版本中（就是GitHub还没发布的版本）点检查更新，马上提醒发现新版本（老的）
比如：
![@N8Y%`XI)VE(5L5SK%79L`7](https://user-images.githubusercontent.com/84891987/215268770-612c96a8-5495-4a76-89de-e29909f76599.png)
所以，ddggdd135，来活了（

### 问题复现率

必现

### 复现步骤

上面说了

### 操作系统版本

Windows

### WonderLab版本

Alpha 1.0.1.7

**Comment by JWJUN233233** [comment]
明天修
