### ISSUE TITLE
关于Build.cmd问题

### ISSUE THREAD

**Issue by Lfhsheng** [Blessing-Studio/WonderLab#33]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab/issues) 列表中是否有相似问题
- [X] 查看 [Releases](https://github.com/Blessing-Studio/WonderLab/releases) 中最新版是否已修复你所遇到的问题
- [X] 查看 [Actions](https://github.com/Blessing-Studio/WonderLab/Actions) 中最新Dev版是否已修复你所遇到的问题

### 问题描述

这cmd里的echo有坑啊，建议不要使用空格

![image](https://user-images.githubusercontent.com/74490140/215272241-5aac8a56-2ce9-4c34-8353-c06e23bdc380.png)

### 问题复现率

必现

### 复现步骤

直接运行[Build.cmd](https://github.com/Blessing-Studio/WonderLab/blob/master/Build.cmd)

### 操作系统版本

全平台

### WonderLab版本

[1.0.1.6](https://github.com/Blessing-Studio/WonderLab/releases/tag/1.0.1.6)

**Comment by JWJUN233233** [comment]
请使用Windows自带cmd后重试 我并没有复现此问题

**Comment by Lfhsheng** [comment]
~~@JWJUN233233 那在README.md直接写上构建方法就可以了~~
