### ISSUE TITLE
Java自动搜素bug

### ISSUE THREAD

**Issue by CaptainOnTheBridge** [Blessing-Studio/WonderLab#36]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab/issues) 列表中是否有相似问题
- [X] 查看 [Releases](https://github.com/Blessing-Studio/WonderLab/releases) 中最新版是否已修复你所遇到的问题
- [X] 查看 [Actions](https://github.com/Blessing-Studio/WonderLab/Actions) 中最新Dev版是否已修复你所遇到的问题

### 问题描述

在使用自动搜索java事会出现两遍
C:\Users\liuli\AppData\Roaming\java\OpenJDK11\jdk-11\bin\javaw.exe
C:\Program Files\java\jdk-11\bin\javaw.exe
C:\Users\liuli\AppData\Roaming\java\OpenJDK11\jdk-11\bin\javaw.exe
C:\Program Files\java\jdk-11\bin\javaw.exe
而且点一次搜索就会接着叠加

### 问题复现率

必现

### 复现步骤

1.java设置
2.自动搜索

### 操作系统版本

Windows

### WonderLab版本

1.0.1.7

**Comment by JWJUN233233** [comment]
自动去重出了问题
