### ISSUE TITLE
[bug] 不能用的自定义下载

### ISSUE THREAD

**Issue by china-us** [Blessing-Studio/WonderLab#38]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab/issues) 列表中是否有相似问题
- [X] 查看 [Releases](https://github.com/Blessing-Studio/WonderLab/releases) 中最新版是否已修复你所遇到的问题
- [X] 查看 [Actions](https://github.com/Blessing-Studio/WonderLab/Actions) 中最新Dev版是否已修复你所遇到的问题

### 问题描述

点 自定义下载 无反应

### 问题复现率

必现

### 复现步骤

首先启动最新的wonderlab 然后点祝福终端 最后点自定义下载

### 操作系统版本

Windows

### WonderLab版本

1.0.1.8

**Comment by JWJUN233233** [comment]
现在都还没有1.0.1.8呢 我会尝试修复这个bug
