### ISSUE TITLE
直接启动游戏后，配置不会保存

### ISSUE THREAD

**Issue by TwilightNougat** [Blessing-Studio/WonderLab#4]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab/issues) 列表中是否有相似问题
- [X] 查看 [Releases](https://github.com/Blessing-Studio/WonderLab/releases) 中最新版是否已修复你所遇到的问题

### 问题描述

1. 直接启动游戏后，配置不会保存，必须要手动关闭wonderlab窗口才能保存java路径游戏目录游戏档案等配置。

2. 内容下载完成后进度条不会走到头，大概到70%左右的位置，但是内容已经下载完了。

ps：这个启动器是目前用过启动速度最快的，比pcl启动器精简而且方便，很喜欢，感谢开发者。

### 问题复现率

必现

### 复现步骤

点击启动游戏，启动器窗口自动关闭，下次打开启动器后没有保存配置信息，还要重新设置

### 操作系统版本

Windows

### WonderLab版本

1.0.1.1

**Comment by TwilightNougat** [comment]
新bug，取消java下载时出现乱码提示框

**Comment by JWJUN233233** [comment]
这些bug春节来修 明天我还要加版本控制

**Comment by TwilightNougat** [comment]
小bug，模组界面，拉到底显示不全

**Comment by JWJUN233233** [comment]
> 新bug，取消java下载时出现乱码提示框

我并没有成功复现此bug 可能是你的问题
