### ISSUE TITLE
字体显示错误

### ISSUE THREAD

**Issue by fuyanbo123** [Blessing-Studio/WonderLab#40]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab/issues) 列表中是否有相似问题
- [X] 查看 [Releases](https://github.com/Blessing-Studio/WonderLab/releases) 中最新版是否已修复你所遇到的问题
- [X] 查看 [Actions](https://github.com/Blessing-Studio/WonderLab/Actions) 中最新Dev版是否已修复你所遇到的问题

### 问题描述

使用时，英文字体显示乱码。

### 问题复现率

必现

### 复现步骤

打开时

### 操作系统版本

Mac

### WonderLab版本

1.0.1.5

**Comment by fuyanbo123** [comment]
应该是表情包，或是一些其他的字符显示乱码

**Comment by hei-shou** [comment]
修好了
