### ISSUE TITLE
离线验证设置uuid

### ISSUE THREAD

**Issue by Xiepohe** [Blessing-Studio/WonderLab#41]
### 建议描述

创建离线验证账户时可以提供一个填写uuid的框
方便从其他启动器把已有的离线账户迁移到本启动器

### 操作系统版本

Windows

### WonderLab版本

Release 1.0.1.6

**Comment by Blessing-Studio** [comment]
ok了

**Comment by Blessing-Studio** [comment]
你的议题已解决
感谢反馈
[点击这里反馈新问题](https://github.com/Blessing-Studio/WonderLab/issues/new/choose)
