### ISSUE TITLE
在 Intel Mac 上无法启动

### ISSUE THREAD

**Issue by Bejukoro** [Blessing-Studio/WonderLab#42]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab/issues) 列表中是否有相似问题
- [X] 查看 [Releases](https://github.com/Blessing-Studio/WonderLab/releases) 中最新版是否已修复你所遇到的问题
- [X] 查看 [Actions](https://github.com/Blessing-Studio/WonderLab/Actions) 中最新Dev版是否已修复你所遇到的问题

### 问题描述

在运行 macOS 13.0.1 的 MacBook Pro 2018 13" 上，无法运行 Intel 版本的 WonderLab。

一开始会出现“WonderLab 已损坏”的报错。
移除 dmg 的 quarantine 属性后不再报错，但依然无法打开 WonderLab。

具体表现为：
- 点击图标后没有出现任何窗口；
- WonderLab 没有在“活动监视器”中出现；
- “强制退出”窗口中，WonderLab 出现一瞬间便消失。

### 问题复现率

必现

### 复现步骤

1. 将 dmg 中的 WonderLab 应用拖拽到应用程序文件夹；
2. 在 LaunchPad 中打开 WonderLab；
3. 提示“WonderLab 已损坏”；
![9c1eccdc08fb889c343a1cf2d33c258f](https://user-images.githubusercontent.com/42836326/216497461-d1fa3bef-8d3b-445b-9a4f-5e70e0035e3e.png)
4. 删除 WonderLab 后，移除 dmg 的 quarantine 属性，然后重复第 1 和第 2 步；
5. WonderLab 图标在 Dock 栏跳动几下，之后什么都没有发生。

### 操作系统版本

Mac

### WonderLab版本

未知。dmg 文件名没有标注版本号；因为无法打开应用，也无法在应用中确认。
此版本下载自测试二群（因为 Releases 中只有 M1 版本），上传时间为 1 月 21 日。

**Comment by JWJUN233233** [comment]
耐心等待下一次构建

**Comment by chengzhilin2021** [comment]
在关闭后，打开系统偏好设置，选择安全性与隐私，选择通用，点击允许打开

**Comment by Blessing-Studio** [comment]
你的议题已解决
感谢反馈
[点击这里反馈新问题](https://github.com/Blessing-Studio/WonderLab/issues/new/choose)
