### ISSUE TITLE
[建议]补充readme

### ISSUE THREAD

**Issue by cxykevin** [Blessing-Studio/WonderLab#5]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab/issues) 列表中是否有相似问题
- [X] 查看 [Releases](https://github.com/Blessing-Studio/WonderLab/releases) 中最新版是否已修复你所遇到的问题

### 问题描述

readme中少东西
+ 没有编译方法
    最好能有一键编译脚本
+ 没有贡献规范(pr要求)

### 问题复现率

必现

### 复现步骤

无

### 操作系统版本

Linux

### WonderLab版本

与版本无关

**Comment by JWJUN233233** [comment]
那我直接添加个Windows 自动编译脚本

**Comment by xiaoniaoawa** [comment]
> 那我直接添加个Windows 自动编译脚本

哈哈哈哈草

**Comment by JWJUN233233** [comment]
完成

**Comment by cxykevin** [comment]
并不建议只添加bat，而是建议使用makefile，跨平台，可以自动构建依赖，避免重复构建

**Comment by cxykevin** [comment]
cmake送GNU make
