### ISSUE TITLE
Archlinux中安装"WonderLab"后无法打开

### ISSUE THREAD

**Issue by chengzhilin2021** [Blessing-Studio/WonderLab#50]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab/issues) 列表中是否有相似问题
- [X] 查看 [Releases](https://github.com/Blessing-Studio/WonderLab/releases) 中最新版是否已修复你所遇到的问题
- [X] 查看 [Actions](https://github.com/Blessing-Studio/WonderLab/Actions) 中最新Dev版是否已修复你所遇到的问题

### 问题描述

桌面环境
===
* Plasma5.27
* X11环境

安装方式
===
* 使用[提供的PKGBUILD](https://github.com/Blessing-Studio/WonderLab/blob/master/WonderLabAur/PKGBUILD)
* 使用[Aur(Wonderlab)](https://aur.archlinux.org/packages/wonderlab)或[Aur(Wonderlab-git)](https://aur.archlinux.org/packages/wonderlab-git)
* 自行编译

错误提示
===
* **找不到程序“/usr/share/wonderlab/wonderlab 找不到testapp"**

### 问题复现率

必现

### 复现步骤

* **1. 执行yay -S wonderlab或在有PKGBUILD的路径下执行makepkg -si命令**
* **2. 单击开始菜单，搜索wonderlab，出现"testapp"后单击**
* **3.右下角弹出错误提示**

### 操作系统版本

Linux

### WonderLab版本

1.0.1.6

**Comment by JWJUN233233** [comment]
使用deb或rpm安装

**Comment by Blessing-Studio** [comment]
你的议题已解决
感谢反馈
[点击这里反馈新问题](https://github.com/Blessing-Studio/WonderLab/issues/new/choose)
