### ISSUE TITLE
在Ubuntu中安装wonderlab后找不到软件

### ISSUE THREAD

**Issue by Titan87zs** [Blessing-Studio/WonderLab#55]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab/issues) 列表中是否有相似问题
- [X] 查看 [Releases](https://github.com/Blessing-Studio/WonderLab/releases) 中最新版是否已修复你所遇到的问题
- [X] 查看 [Actions](https://github.com/Blessing-Studio/WonderLab/Actions) 中最新Dev版是否已修复你所遇到的问题

### 问题描述

安装linx-x86_64.deb档案后在软件搜索栏中找不到wonderlab

### 问题复现率

必现

### 复现步骤

1. 在ubuntu系统中安装wonderlab
2. 在软件搜索栏中输入wonderlab

### 操作系统版本

Linux

### WonderLab版本

1.0.1.6

**Comment by JWJUN233233** [comment]
请到github actions自动构建下载 原有版本已废弃

**Comment by JWJUN233233** [comment]
此版本已不受支持

**Comment by JWJUN233233** [comment]
如果依然存在问题 请重新对此issue进行评论

**Comment by JWJUN233233** [comment]
这确实是个bug 暂时没解决方案

**Comment by JWJUN233233** [comment]
已找到解决方案 很快将会修复

**Comment by JWJUN233233** [comment]
已修复

**Comment by Blessing-Studio** [comment]
你的议题已解决
感谢反馈
[点击这里反馈新问题](https://github.com/Blessing-Studio/WonderLab/issues/new/choose)
