### ISSUE TITLE
[建议]建议添加自定义项

### ISSUE THREAD

**Issue by xiaoniaoawa** [Blessing-Studio/WonderLab#6]
### 建议描述

比如自定义背景啊，启动器播放器啊一类的
可以参考参考PCL？(划掉)
-------------

1. 加入自定义背景
2. 加入启动器内播放器
3. 参考PCL加入百宝箱与千万别点...?
4. 优化几下下载问题（群里人都说了对吧）
5. 解决其他问题

### 操作系统版本

Windows

### WonderLab版本

Latest1.0.1.0 - Latest1.0.1.2

**Comment by JWJUN233233** [comment]
播放器以前是有的(还没发视频宣传的时候) 到时候弄一下
第5项不明确
第3项暂时不加

**Comment by Blessing-Studio** [comment]
下载器的问题目前修好了，明天发构建
