### ISSUE TITLE
提供软件更新的下载源

### ISSUE THREAD

**Issue by 6get-xiaofan** [Blessing-Studio/WonderLab#7]
### 建议描述

对于国内用户来说，GitHub下载确实会很慢，有时直接无法访问，建议提供Gitee下载源

### 操作系统版本

Windows

### WonderLab版本

1.0.8

**Comment by JWJUN233233** [comment]
过几天做 现在挺忙

**Comment by Lfhsheng** [comment]
感觉蓝奏云挺不错（至少不像某盘限速

**Comment by JWJUN233233** [comment]
> 感觉蓝奏云挺不错（至少不像某盘限速

但是这样没法获取更新
