### ISSUE TITLE
关于每次打开有99%机率崩的问题

### ISSUE THREAD

**Issue by xiaoniaoawa** [Blessing-Studio/WonderLab#8]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab/issues) 列表中是否有相似问题
- [X] 查看 [Releases](https://github.com/Blessing-Studio/WonderLab/releases) 中最新版是否已修复你所遇到的问题

### 问题描述

`Application: WonderLab.exe
CoreCLR Version: 6.0.1322.58009
.NET Version: 6.0.13
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at WonderLab.App.<>c.<<CheckAsync>b__9_0>d.MoveNext() in D:\a\WonderLab\WonderLab\WonderLab\App.axaml.cs:line 78
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
`

--------------------------

`错误应用程序名称: WonderLab.exe，版本: 1.0.0.0，时间戳: 0x6387d353
错误模块名称: KERNELBASE.dll，版本: 10.0.22000.1335，时间戳: 0x003161e5
异常代码: 0xe0434352
错误偏移量: 0x000000000004441c
错误进程 ID: 0x192c
错误应用程序启动时间: 0x01d92c95376a7737
错误应用程序路径: F:\Minecraft\WonderLab\WonderLab.exe
错误模块路径: C:\Windows\System32\KERNELBASE.dll
报告 ID: 877adb12-22ea-4024-9543-3d2fd9684604
错误程序包全名: 
错误程序包相对应用程序 ID: `

### 问题复现率

必现

### 复现步骤

1.点两下启动器打开

没了

### 操作系统版本

Windows

### WonderLab版本

NET6.0.13
WonderLab1.0.1.2

**Comment by JWJUN233233** [comment]
试试最新版本 我修了个null报错 看看你那里好没有

**Comment by xiaoniaoawa** [comment]
> 试试最新版本 我修了个null报错 看看你那里好没有

okok我试试( )

**Comment by xiaoniaoawa** [comment]
> 试试最新版本 我修了个null报错 看看你那里好没有

Fail-Fix #2 一处可能出现null报错的地方 #12
《 编 译 失 败 》
修了个寂寞（（（

**Comment by JWJUN233233** [comment]
az

**Comment by JWJUN233233** [comment]
c 他们ui的没写好

**Comment by JWJUN233233** [comment]
> > 试试最新版本 我修了个null报错 看看你那里好没有
> 
> Fail-Fix #2 一处可能出现null报错的地方 #12 《 编 译 失 败 》 修了个寂寞（（（

现在好了 自己去actions

**Comment by JWJUN233233** [comment]
![image](https://user-images.githubusercontent.com/66861021/213643766-0551f3b6-7962-478e-b0d5-169678185d16.png)
找到哪里有bug了

**Comment by xiaoniaoawa** [comment]
okok

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Ddggdd135 ***@***.***>
发送时间: Friday, January 20, 2023 3:48:40 PM
收件人: Blessing-Studio/WonderLab ***@***.***>
抄送: xiaoniao_ ***@***.***>; Author ***@***.***>
主题: Re: [Blessing-Studio/WonderLab] 关于每次打开有99%机率崩的问题 (Issue #8)


[image]<https://user-images.githubusercontent.com/66861021/213643766-0551f3b6-7962-478e-b0d5-169678185d16.png>
找到哪里有bug了

―

**Comment by JWJUN233233** [comment]
已修复

**Comment by sulianhongjing** [comment]
现在启动一些带forge的还是基本上直接闪退是咋回事

**Comment by xiaoniaoawa** [comment]
我不到啊，修完闪退我还没试呐…

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: sulianhongjing ***@***.***>
发送时间: Friday, January 20, 2023 4:32:40 PM
收件人: Blessing-Studio/WonderLab ***@***.***>
抄送: xiaoniao_ ***@***.***>; Author ***@***.***>
主题: Re: [Blessing-Studio/WonderLab] 关于每次打开有99%机率崩的问题 (Issue #8)


现在启动一些带forge的还是基本上直接闪退是咋回事

―
